# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test: &test
  <<: *default

development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: burak
  password:

cucumber:
  <<: *test

#production:
# adapter: postgresql
# host: 'ec2-54-225-157-157.compute-1.amazonaws.com'
# username: 'llxaabzuyauvni'
# database: 'dd6sn5903aaap4'
# password: '5SopTzuz1tUr9jBp9WSy4ULPD3'